### ISSUE TITLE
Glenn's media player wall - some not starting

### ISSUE THREAD

**Issue by sighmon** [ACMILabs/media-player#146]
- [x] Before starting `media-player.py` check that the env var `DISPLAY`, `SCREEN_WIDTH` and `SCREEN_HEIGHT` is set, if not restart the `mediaplayer` container
- [x] Try setting `RESIN_HOST_CONFIG_hdmi_drive` to `2` #155
- [x] ~Try setting screen resolution in [config.txt](https://www.raspberrypi.org/documentation/configuration/config-txt/video.md) to 60Hz 1080p 16x9: `RESIN_HOST_CONFIG_hdmi_group=1` and `RESIN_HOST_CONFIG_hdmi_mode=16`~ #158 - didn't help
- [x] The `mediaplayer` container is failing to connect to the supervisor the first time, so try in a loop #159

See: [FSF-04-AV01-RP49-RP49](https://dashboard.balena-cloud.com/devices/ea3e815d4c342a30451a928bec829ac8/summary)

## Error after fix

```bash
25.01.21 11:30:23 (+1030) Supervisor starting
25.01.21 10:30:20 (+1030)  mediaplayer  STARTING X
25.01.21 10:30:22 (+1030)  mediaplayer  
25.01.21 11:30:18 (+1030)  mediaplayer  
25.01.21 11:30:18 (+1030)  mediaplayer  X.Org X Server 1.20.4
25.01.21 11:30:18 (+1030)  mediaplayer  X Protocol Version 11, Revision 0
25.01.21 11:30:18 (+1030)  mediaplayer  Build Operating System: Linux 5.4.0-54-generic armv8l Raspbian
25.01.21 11:30:18 (+1030)  mediaplayer  Current Operating System: Linux a2a323d498d0 5.4.58 #1 SMP PREEMPT Wed Nov 11 13:05:46 UTC 2020 aarch64
25.01.21 11:30:18 (+1030)  mediaplayer  Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 video=HDMI-A-1:1920x1080M@60,margin_left=48,margin_right=48,margin_top=48,margin_bottom=48 smsc95xx.macaddr=DC:A6:32:50:D4:0A vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  dwc_otg.lpm_enable=0 console=null rootfstype=ext4 rootwait vt.global_cursor_default=0 root=UUID=ba1eadef-4b05-40cb-96a2-8015cf74b254 rootwait
25.01.21 11:30:18 (+1030)  mediaplayer  Build Date: 01 December 2020  05:59:57PM
25.01.21 11:30:18 (+1030)  mediaplayer  xorg-server 2:1.20.4-1+rpt2+deb10u2 (https://www.debian.org/support) 
25.01.21 11:30:18 (+1030)  mediaplayer  Current version of pixman: 0.36.0
25.01.21 11:30:18 (+1030)  mediaplayer          Before reporting problems, check http://wiki.x.org
25.01.21 11:30:18 (+1030)  mediaplayer          to make sure that you have the latest version.
25.01.21 11:30:18 (+1030)  mediaplayer  Markers: (--) probed, (**) from config file, (==) default setting,
25.01.21 11:30:18 (+1030)  mediaplayer          (++) from command line, (!!) notice, (II) informational,
25.01.21 11:30:18 (+1030)  mediaplayer          (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
25.01.21 11:30:18 (+1030)  mediaplayer  (==) Log file: "/var/log/Xorg.2.log", Time: Mon Jan 25 01:00:18 2021
25.01.21 11:30:18 (+1030)  mediaplayer  (==) Using system config directory "/usr/share/X11/xorg.conf.d"
25.01.21 11:30:21 (+1030)  mediaplayer  (II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
25.01.21 11:30:21 (+1030)  mediaplayer  Displays in use after starting X
25.01.21 11:30:21 (+1030)  mediaplayer  DISPLAY=:0
25.01.21 11:30:21 (+1030)  mediaplayer  Setting display to: DISPLAY=:0
25.01.21 11:30:21 (+1030)  mediaplayer  xset:  unable to open display ":0"
25.01.21 11:30:21 (+1030)  mediaplayer  unclutter: could not open display
25.01.21 11:30:21 (+1030)  mediaplayer  Can't open display :0
25.01.21 11:30:21 (+1030)  mediaplayer  Can't open display :0
25.01.21 11:30:21 (+1030)  mediaplayer  Screen resolution parsed as: x
25.01.21 11:30:21 (+1030)  mediaplayer  ERROR: DISPLAY, SCREEN_WIDTH or SCREEN_HEIGHT isn't set, so restarting the media player container: :0, x
25.01.21 11:30:22 (+1030)  mediaplayer  curl: (7) Failed to connect to 10.114.104.1 port 48484: Connection refused
```

## Error details

Some devices on first boot aren't detecting their display:

```
15.01.21 11:08:54 (+1030)  mediaplayer  DISPLAY=:0
15.01.21 11:08:54 (+1030)  mediaplayer  Setting display to: DISPLAY=:0
15.01.21 11:08:54 (+1030)  mediaplayer  xset:  unable to open display ":0"
15.01.21 11:08:54 (+1030)  mediaplayer  unclutter: could not open display
15.01.21 11:08:54 (+1030)  mediaplayer  Can't open display :0
15.01.21 11:08:54 (+1030)  mediaplayer  Can't open display :0
15.01.21 11:08:54 (+1030)  mediaplayer  Screen resolution parsed as: x
```
